require("plugins.lazy")
require("plugins.autopair")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.blamer")
require("plugins.dap")
require("plugins.hop")
require("plugins.gitsigns")

